version: "2"
output:
  formats:
    text:
      path: stdout
      color: true
linters:
  default: all
  disable:
    - gochecknoglobals
    - gochecknoinits
    - mnd
    - wsl
  settings:
    lll:
      line-length: 140
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
