name: Review
on: [pull_request]
jobs:

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-golangci-lint@v8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
